"""Ancillary Services reports from the OASIS menu. See docs/caiso_oasis.md for sources."""

from .models import CategoryScraper, Report

REPORTS = (
    Report(
        "AS_REQ",
        "DAM",
        1,
        1,
        "dam_as_requirements",
        menu="AS Requirements",
        description="AS Requirements",
        parameters=(("anc_type", "ALL"), ("anc_region", "ALL")),
    ),
    Report(
        "AS_REQ",
        "HASP",
        1,
        1,
        "hasp_as_requirements",
        menu="AS Requirements",
        description="AS Requirements",
        parameters=(("anc_type", "ALL"), ("anc_region", "ALL")),
    ),
    Report(
        "AS_REQ",
        "RTM",
        1,
        1,
        "rtm_as_requirements",
        menu="AS Requirements",
        description="AS Requirements",
        parameters=(("anc_type", "ALL"), ("anc_region", "ALL")),
    ),
    Report(
        "AS_RESULTS",
        "DAM",
        1,
        1,
        "dam_as_results",
        menu="AS Results",
        description="AS Results",
        parameters=(("anc_type", "ALL"), ("anc_region", "ALL")),
    ),
    Report(
        "AS_RESULTS",
        "HASP",
        1,
        1,
        "hasp_as_results",
        menu="AS Results",
        description="AS Results",
        parameters=(("anc_type", "ALL"), ("anc_region", "ALL")),
    ),
    Report(
        "AS_RESULTS",
        "RTM",
        1,
        1,
        "rtm_as_results",
        menu="AS Results",
        description="AS Results",
        parameters=(("anc_type", "ALL"), ("anc_region", "ALL")),
    ),
    Report(
        "AS_OP_RSRV",
        None,
        1,
        1,
        "actual_operating_reserves",
        menu="Actual Operating Reserves",
        description="Actual operating reserves",
        source="spec_2019",
    ),
    Report(
        "AS_MILEAGE_CALC",
        None,
        1,
        1,
        "as_mileage_components",
        menu="Mileage Calculation Components",
        description="Mileage accuracy and multiplier components",
        source="spec_2019",
        parameters=(("anc_type", "ALL"),),
    ),
)

SCRAPER = CategoryScraper("ancillary_services", REPORTS, ())
