"""Energy reports from the OASIS menu. See docs/caiso_oasis.md for sources."""

from .models import CategoryScraper, Report

REPORTS = (
    Report(
        "ENE_SLRS",
        "DAM",
        1,
        1,
        "dam_load_resource_schedules",
        menu="Schedule",
        description="System load and resource schedules",
        parameters=(("tac_zone_name", "ALL"), ("schedule", "ALL")),
    ),
    Report(
        "ENE_SLRS",
        "HASP",
        1,
        1,
        "hasp_load_resource_schedules",
        menu="Schedule",
        description="System load and resource schedules",
        parameters=(("tac_zone_name", "ALL"), ("schedule", "ALL")),
    ),
    Report(
        "ENE_SLRS",
        "RTM",
        1,
        1,
        "rtm_load_resource_schedules",
        menu="Schedule",
        description="System load and resource schedules",
        parameters=(("tac_zone_name", "ALL"), ("schedule", "ALL")),
    ),
    Report(
        "ENE_SLRS",
        "RUC",
        1,
        1,
        "ruc_load_resource_schedules",
        menu="Schedule",
        description="System load and resource schedules",
        parameters=(("tac_zone_name", "ALL"), ("schedule", "ALL")),
    ),
    Report(
        "ENE_DISP",
        None,
        1,
        1,
        "system_dispatch",
        menu="System",
        description="System results",
        source="spec_2019",
    ),
    Report(
        "ENE_EA",
        None,
        2,
        1,
        "energy_available",
        menu="System",
        description="System results",
        source="spec_2019",
        parameters=(("energy_type", "ALL"), ("opr_interval", "ALL")),
    ),
    Report(
        "ENE_LOSS",
        "DAM",
        1,
        1,
        "dam_system_losses",
        menu="System",
        description="System results",
        source="spec_2019",
    ),
    Report(
        "ENE_FLEX_RAMP_REQT",
        "RTD",
        4,
        1,
        "rtd_flexible_ramp_requirements",
        menu="Flexible Ramping",
        description="Flexible Ramping results",
        source="spec_2019",
        parameters=(("baa_grp_id", "ALL"),),
    ),
    Report(
        "ENE_AGGR_FLEX_RAMP",
        "RTD",
        4,
        1,
        "rtd_aggregate_flexible_ramp",
        menu="Flexible Ramping",
        description="Flexible Ramping results",
        source="spec_2019",
        parameters=(("baa_grp_id", "ALL"),),
    ),
    Report(
        "ENE_FLEX_RAMP_DC",
        "RTD",
        4,
        1,
        "rtd_flexible_ramp_credits",
        menu="Flexible Ramping",
        description="Flexible Ramping results",
        source="spec_2019",
        parameters=(("baa_grp_id", "ALL"),),
    ),
    Report(
        "ENE_UNCERTAINTY_MV",
        "RTD",
        4,
        1,
        "rtd_uncertainty_movement",
        menu="Flexible Ramping",
        description="Flexible Ramping results",
        source="spec_2019",
        parameters=(("baa_grp_id", "ALL"),),
    ),
    Report(
        "ENE_CB_AWARDS",
        None,
        1,
        1,
        "convergence_bid_awards",
        menu="Convergence Bidding",
        description="Convergence Bidding results",
        source="spec_2019",
    ),
    Report(
        "ENE_CB_CLR_AWARDS",
        None,
        1,
        1,
        "convergence_bid_cleared_awards",
        menu="Convergence Bidding",
        description="Convergence Bidding results",
        source="spec_2019",
    ),
    Report(
        "ENE_CB_MKT_SUM",
        None,
        1,
        1,
        "convergence_bid_market_summary",
        menu="Convergence Bidding",
        description="Convergence Bidding results",
        source="spec_2019",
    ),
    Report(
        "ENE_EIM_TRANSFER_TIE",
        "RTD",
        4,
        1,
        "rtd_eim_tie_transfers",
        menu="Energy Imbalance Market",
        description="Energy Imbalance Market results",
        source="spec_2019",
        parameters=(("baa_grp_id", "ALL"),),
    ),
    Report(
        "ENE_EIM_TRANSFER_LIMITS_TIE",
        "RTD",
        5,
        1,
        "rtd_eim_tie_transfer_limits",
        menu="Energy Imbalance Market",
        description="Energy Imbalance Market results",
        source="spec_2019",
        parameters=(("baa_grp_id", "ALL"),),
    ),
    Report(
        "ENE_EIM_TRANSFER",
        "ALL",
        2,
        1,
        "eim_transfers",
        menu="Energy Imbalance Market",
        description="Energy Imbalance Market results",
        source="spec_2019",
        parameters=(("baa_grp_id", "ALL"),),
    ),
    Report(
        "ENE_EIM_TRANSFER_LIMITS",
        "ALL",
        2,
        1,
        "eim_transfer_limits",
        menu="Energy Imbalance Market",
        description="Energy Imbalance Market results",
        source="spec_2019",
        parameters=(("baa_grp_id", "ALL"),),
    ),
    Report(
        "ENE_EIM_FLEX_RAMP_INPUT",
        "RTM",
        6,
        1,
        "eim_flexible_ramp_inputs",
        menu="Energy Imbalance Market",
        description="Energy Imbalance Market results",
        source="spec_2019",
        parameters=(("baa_grp_id", "ALL"), ("snapshot_indicator", "ALL")),
    ),
    Report(
        "ENE_RES_UPL_GRP",
        None,
        8,
        1,
        "resource_uplift",
        menu="Uplift",
        description="Uplift and operator instruction costs",
        endpoint="GroupZip",
        source="spec_2019",
    ),
    Report(
        "ENE_ZNL_UPL_GRP",
        None,
        8,
        1,
        "zonal_uplift",
        menu="Uplift",
        description="Uplift and operator instruction costs",
        endpoint="GroupZip",
        source="spec_2019",
    ),
    Report(
        "ENE_OIC_GRP",
        None,
        8,
        1,
        "operator_instruction_costs",
        menu="Uplift",
        description="Uplift and operator instruction costs",
        endpoint="GroupZip",
        source="spec_2019",
    ),
    Report(
        "DAM_CAP_PRC_GRP",
        None,
        1,
        1,
        "dam_imbalance_reserve_prices",
        menu="Imbalance Reserve",
        description="Imbalance reserve and reliability capacity prices",
        endpoint="GroupZip",
    ),
    Report(
        "DAM_CAP_REQ_AWRD_GRP",
        None,
        1,
        1,
        "dam_imbalance_reserve_awards",
        menu="Imbalance Reserve",
        description="Imbalance reserve and reliability capacity requirements and awards",
        endpoint="GroupZip",
    ),
    Report(
        "2DA_CAP_REQ_AWRD_GRP",
        None,
        1,
        1,
        "2da_imbalance_reserve_awards",
        menu="Imbalance Reserve",
        description="Imbalance reserve and reliability capacity requirements and awards",
        endpoint="GroupZip",
    ),
    Report(
        "3DA_CAP_REQ_AWRD_GRP",
        None,
        1,
        1,
        "3da_imbalance_reserve_awards",
        menu="Imbalance Reserve",
        description="Imbalance reserve and reliability capacity requirements and awards",
        endpoint="GroupZip",
    ),
    Report(
        "DAM_TOTAL_NET_GHG_IMP_TRNSFR_GRP",
        None,
        1,
        1,
        "edam_ghg_import_transfers",
        menu="EDAM",
        description="edam ghg import transfers",
        source="portal",
        endpoint="GroupZip",
    ),
    Report(
        "DAM_AGG_BAA_LVL_FINAL_BIND_GRP",
        None,
        1,
        1,
        "edam_baa_rse_tests",
        menu="EDAM",
        description="edam baa rse tests",
        source="portal",
        endpoint="GroupZip",
        numeric_columns=("requirement_amount", "supply", "total_transfer"),
    ),
    Report(
        "EDAM_NET_EXP_TRNS_CNSTR_INP_PRM_GRP",
        None,
        1,
        1,
        "edam_net_export_constraints",
        menu="EDAM",
        description="edam net export constraints",
        source="portal",
        endpoint="GroupZip",
    ),
    Report(
        "DAM_TAG_TRANS_ENE_STATUS_GRP",
        None,
        1,
        1,
        "edam_tagged_energy_profiles",
        menu="EDAM",
        description="edam tagged energy profiles",
        source="portal",
        endpoint="GroupZip",
    ),
    Report(
        "DAM_MKT_BA_COMP_GRP",
        None,
        1,
        1,
        "edam_market_ba_composition",
        menu="EDAM",
        description="edam market ba composition",
        source="portal",
        endpoint="GroupZip",
    ),
    Report(
        "DAM_BAA_AGG_TRNSFR_GRP",
        None,
        1,
        1,
        "edam_baa_aggregated_transfers",
        menu="EDAM",
        description="edam baa aggregated transfers",
        source="portal",
        endpoint="GroupZip",
    ),
)

SCRAPER = CategoryScraper("energy", REPORTS)
