"""Prices reports from the OASIS menu. See docs/caiso_oasis.md for sources."""

from .models import CategoryScraper, Report

REPORTS = (
    Report(
        "PRC_LMP",
        "DAM",
        12,
        15,
        "dam_lmp",
        menu="Energy Prices",
        description="Hourly day-ahead locational marginal prices",
        requires_node=True,
        interval_minutes=60,
        required_components=("LMP", "MCE", "MCC", "MCL"),
    ),
    Report(
        "PRC_INTVL_LMP",
        "RTM",
        3,
        1,
        "rtm_lmp",
        menu="Energy Prices",
        description="Five-minute real-time dispatch locational marginal prices",
        requires_node=True,
        interval_minutes=5,
        required_components=("LMP", "MCE", "MCC", "MCL"),
    ),
    Report(
        "PRC_RTPD_LMP",
        "RTPD",
        3,
        1,
        "fmm_lmp",
        menu="Energy Prices",
        description="Fifteen-minute market locational marginal prices",
        requires_node=True,
        interval_minutes=15,
        required_components=("LMP", "MCE", "MCC", "MCL"),
    ),
    Report(
        "PRC_HASP_LMP",
        None,
        3,
        1,
        "hasp_lmp",
        menu="Energy Prices",
        description="Hour-ahead scheduling process prices",
        requires_node=True,
        interval_minutes=15,
        required_components=("LMP", "MCE", "MCC", "MCL"),
    ),
    Report(
        "PRC_SPTIE_LMP",
        "DAM",
        5,
        1,
        "dam_scheduling_point_lmp",
        menu="Energy Prices",
        description="Scheduling-point/tie combination prices",
        requires_node=True,
    ),
    Report(
        "PRC_SPTIE_LMP",
        "RTD",
        5,
        1,
        "rtd_scheduling_point_lmp",
        menu="Energy Prices",
        description="Scheduling-point/tie combination prices",
        requires_node=True,
    ),
    Report(
        "PRC_SPTIE_LMP",
        "RTPD",
        5,
        1,
        "rtpd_scheduling_point_lmp",
        menu="Energy Prices",
        description="Scheduling-point/tie combination prices",
        requires_node=True,
    ),
    Report(
        "PRC_CNSTR",
        "DAM",
        1,
        1,
        "dam_intertie_shadow_prices",
        menu="Shadow Prices",
        description="Constraint shadow prices",
        source="spec_2019",
        parameters=(("ti_id", "ALL"),),
    ),
    Report(
        "PRC_NOMOGRAM",
        "DAM",
        1,
        1,
        "dam_nomogram_shadow_prices",
        menu="Shadow Prices",
        description="Constraint shadow prices",
        source="spec_2019",
        parameters=(("nomogram_id", "ALL"),),
    ),
    Report(
        "PRC_RTM_NOMOGRAM",
        None,
        1,
        1,
        "rtm_nomogram_shadow_prices",
        menu="Shadow Prices",
        description="Constraint shadow prices",
        source="spec_2019",
    ),
    Report(
        "PRC_RTM_FLOWGATE",
        None,
        1,
        1,
        "rtm_intertie_shadow_prices",
        menu="Shadow Prices",
        description="Constraint shadow prices",
        source="spec_2019",
    ),
    Report(
        "PRC_DAM_SCH_CNSTR",
        "DAM",
        8,
        1,
        "dam_scheduling_constraint_prices",
        menu="Shadow Prices",
        description="Constraint shadow prices",
        source="spec_2019",
    ),
    Report(
        "PRC_RTM_SCH_CNSTR",
        "RTD",
        4,
        1,
        "rtd_scheduling_constraint_prices",
        menu="Shadow Prices",
        description="Constraint shadow prices",
        source="spec_2019",
    ),
    Report(
        "PRC_AS",
        "DAM",
        12,
        1,
        "dam_as_prices",
        menu="Ancillary Services Prices",
        description="Cleared ancillary service prices",
        parameters=(("anc_type", "ALL"), ("anc_region", "ALL")),
    ),
    Report(
        "PRC_AS",
        "HASP",
        12,
        1,
        "hasp_as_prices",
        menu="Ancillary Services Prices",
        description="Cleared ancillary service prices",
        parameters=(("anc_type", "ALL"), ("anc_region", "ALL")),
    ),
    Report(
        "PRC_INTVL_AS",
        "RTM",
        1,
        1,
        "rtm_as_prices",
        menu="Ancillary Services Prices",
        description="Cleared ancillary service prices",
        parameters=(("anc_type", "ALL"), ("anc_region", "ALL")),
    ),
    Report(
        "PRC_FUEL",
        None,
        1,
        1,
        "fuel_prices",
        menu="Index Prices",
        description="Fuel price indices by fuel region",
        parameters=(("fuel_region_id", "ALL"),),
    ),
    Report(
        "PRC_GHG_ALLOWANCE",
        None,
        1,
        1,
        "ghg_allowance_prices",
        menu="Index Prices",
        description="Greenhouse gas allowance price index",
    ),
    Report(
        "PRC_MPM_LMP",
        "DAM",
        1,
        1,
        "dam_mpm_lmp",
        menu="Market Power Mitigation",
        description="Market power mitigation price results",
        source="spec_2019",
        parameters=(("grp_type", "ALL_APNODES"),),
    ),
    Report(
        "PRC_MPM_CNSTR",
        "DAM",
        1,
        1,
        "dam_mpm_intertie_prices",
        menu="Market Power Mitigation",
        description="Market power mitigation price results",
        source="spec_2019",
        parameters=(("ti_id", "ALL"),),
    ),
    Report(
        "PRC_MPM_NOMOGRAM",
        "DAM",
        1,
        1,
        "dam_mpm_nomogram_prices",
        menu="Market Power Mitigation",
        description="Market power mitigation price results",
        source="spec_2019",
        parameters=(("nomogram_id", "ALL"),),
    ),
    Report(
        "PRC_MPM_CNSTR_CMP",
        "DAM",
        1,
        1,
        "dam_mpm_constraint_comparison",
        menu="Market Power Mitigation",
        description="Market power mitigation price results",
        source="spec_2019",
    ),
    Report(
        "PRC_MPM_NOMOGRAM_CMP",
        "DAM",
        1,
        1,
        "dam_mpm_nomogram_comparison",
        menu="Market Power Mitigation",
        description="Market power mitigation price results",
        source="spec_2019",
    ),
    Report(
        "PRC_MPM_DEFAULT_CMP",
        "DAM",
        5,
        1,
        "dam_mpm_default_comparison",
        menu="Market Power Mitigation",
        description="Market power mitigation price results",
        source="spec_2019",
    ),
    Report(
        "PRC_MPM_REF_BUS",
        "DAM",
        1,
        1,
        "dam_mpm_reference_prices",
        menu="Market Power Mitigation",
        description="Market power mitigation price results",
        source="spec_2019",
    ),
)

SCRAPER = CategoryScraper("prices", REPORTS, ())

DAM_LMP, RTM_LMP = REPORTS[:2]
