"""Public Bids reports from the OASIS menu. See docs/caiso_oasis.md for sources."""

from .models import CategoryScraper, Report

REPORTS = (
    Report(
        "PUB_DAM_GRP",
        None,
        3,
        1,
        "dam_public_bids",
        menu="Public Bids",
        description="Anonymized energy and ancillary-service bid curves",
        endpoint="GroupZip",
        publication_lag_days=90,
        snapshot=True,
    ),
    Report(
        "PUB_RTM_GRP",
        None,
        3,
        1,
        "rtm_public_bids",
        menu="Public Bids",
        description="Anonymized energy and ancillary-service bid curves",
        endpoint="GroupZip",
        publication_lag_days=90,
        snapshot=True,
    ),
    Report(
        "PUB_CB_DAM_GRP",
        None,
        2,
        1,
        "convergence_public_bids",
        menu="Convergence Bidding Public Bids",
        description="Anonymized convergence bid curves",
        endpoint="GroupZip",
        publication_lag_days=90,
        snapshot=True,
        source="spec_2019",
    ),
    Report(
        "PUB_CRR_BID_SEASONAL_GRP",
        None,
        2,
        1,
        "crr_seasonal_public_bids",
        menu="CRR Public Bids",
        description="Anonymized CRR bid points; publication schedule varies by auction",
        endpoint="GroupZip",
        publication_lag_days=90,
        snapshot=True,
        source="spec_2019",
        numeric_columns=("mwquantity", "crr_price"),
    ),
    Report(
        "PUB_CRR_BID_MONTHLY_GRP",
        None,
        2,
        1,
        "crr_monthly_public_bids",
        menu="CRR Public Bids",
        description="Anonymized CRR bid points; publication schedule varies by auction",
        endpoint="GroupZip",
        publication_lag_days=90,
        snapshot=True,
        source="spec_2019",
        numeric_columns=("mwquantity", "crr_price"),
    ),
    Report(
        "MKT_BID_CAPS_GRP",
        None,
        1,
        1,
        "market_bid_caps",
        menu="Market Bid Caps",
        description="market bid caps",
        source="portal",
        endpoint="GroupZip",
    ),
)

SCRAPER = CategoryScraper("public_bids", REPORTS)
