"""Resource Adequacy reports from the OASIS menu. See docs/caiso_oasis.md for sources."""

from .models import CategoryScraper, Report

REPORTS = (
    Report(
        "CMMT_RA_MLC",
        "DAM",
        1,
        1,
        "dam_ra_minimum_load",
        menu="Resource Adequacy and Minimum Load",
        description="RA capacity committed and minimum-load commitment",
        source="spec_2019",
    ),
    Report(
        "PUB_CSP_OFFER_SET_ANNUAL_GRP",
        None,
        1,
        1,
        "csp_annual_offers",
        menu="CSP Offer",
        description="Anonymized competitive solicitation offers, delayed five quarters",
        endpoint="GroupZip",
        publication_lag_quarters=5,
        snapshot=True,
        source="spec_2019",
    ),
    Report(
        "PUB_CSP_OFFER_SET_MONTHLY_GRP",
        None,
        1,
        1,
        "csp_monthly_offers",
        menu="CSP Offer",
        description="Anonymized competitive solicitation offers, delayed five quarters",
        endpoint="GroupZip",
        publication_lag_quarters=5,
        snapshot=True,
        source="spec_2019",
    ),
    Report(
        "PUB_CSP_OFFER_SET_INTRAMONTHLY_GRP",
        None,
        1,
        1,
        "csp_intramonthly_offers",
        menu="CSP Offer",
        description="Anonymized competitive solicitation offers, delayed five quarters",
        endpoint="GroupZip",
        publication_lag_quarters=5,
        snapshot=True,
        source="spec_2019",
    ),
    Report(
        "PUB_CPM_DESIGNATION",
        None,
        1,
        1,
        "cpm_designations",
        menu="CPM Designations",
        description="cpm designations",
        source="portal",
        snapshot=True,
        same_day_end=True,
    ),
    Report(
        "AVAIL_IMP_CAP_GRP",
        None,
        1,
        1,
        "available_import_capability",
        menu="Available Import Capability",
        description="available import capability",
        source="portal",
        endpoint="GroupZip",
        snapshot=True,
        numeric_columns=(
            "total_imp_allocation",
            "reserved_capability",
            "tradable_capability",
        ),
        date_columns=("ra_period_start_date",),
    ),
    Report(
        "ANNUAL_IMP_CAP_USED_RA_PLAN_GRP",
        None,
        1,
        1,
        "import_capability_ra_plans",
        menu="Import Capability Used in RA Plan Data",
        description="import capability ra plans",
        source="portal",
        endpoint="GroupZip",
        snapshot=True,
        numeric_columns=("total_imp_allocation",),
        date_columns=("ra_period_start_date",),
    ),
)

SCRAPER = CategoryScraper("resource_adequacy", REPORTS)
