"""System Demand reports from the OASIS menu. See docs/caiso_oasis.md for sources."""

from .models import CategoryScraper, Report

REPORTS = (
    Report(
        "SLD_FCST",
        "DAM",
        1,
        15,
        "dam_load_forecast",
        menu="CAISO Demand Forecast",
        description="Hourly day-ahead demand forecast",
    ),
    Report(
        "SLD_FCST",
        "2DA",
        1,
        1,
        "2da_load_forecast",
        menu="CAISO Demand Forecast",
        description="Demand forecast or actual load",
    ),
    Report(
        "SLD_FCST",
        "7DA",
        1,
        1,
        "7da_load_forecast",
        menu="CAISO Demand Forecast",
        description="Demand forecast or actual load",
    ),
    Report(
        "SLD_FCST",
        "ACTUAL",
        1,
        1,
        "actual_load_forecast",
        menu="CAISO Demand Forecast",
        description="Demand forecast or actual load",
    ),
    Report(
        "SLD_FCST_PEAK",
        None,
        1,
        1,
        "peak_demand_forecast",
        menu="CAISO Peak Demand Forecast",
        description="Daily peak demand forecast",
        source="spec_2019",
    ),
    Report(
        "SLD_REN_FCST",
        "DAM",
        1,
        1,
        "dam_wind_solar_forecast",
        menu="Wind and Solar Forecast",
        description="Wind and solar forecast or actual output",
    ),
    Report(
        "SLD_REN_FCST",
        "ACTUAL",
        1,
        1,
        "actual_wind_solar_forecast",
        menu="Wind and Solar Forecast",
        description="Wind and solar forecast or actual output",
    ),
    Report(
        "SLD_REN_FCST",
        "HASP",
        1,
        1,
        "hasp_wind_solar_forecast",
        menu="Wind and Solar Forecast",
        description="Wind and solar forecast or actual output",
    ),
    Report(
        "SLD_REN_FCST",
        "RTD",
        1,
        1,
        "rtd_wind_solar_forecast",
        menu="Wind and Solar Forecast",
        description="Wind and solar forecast or actual output",
    ),
    Report(
        "SLD_REN_FCST",
        "RTPD",
        1,
        1,
        "rtpd_wind_solar_forecast",
        menu="Wind and Solar Forecast",
        description="Wind and solar forecast or actual output",
    ),
    Report(
        "SLD_ADV_FCST",
        "RTD",
        4,
        1,
        "rtd_advisory_load_forecast",
        menu="Advisory CAISO Demand Forecast",
        description="Advisory real-time demand forecast",
        source="spec_2019",
    ),
    Report(
        "SLD_ADV_FCST",
        "RTPD",
        4,
        1,
        "rtpd_advisory_load_forecast",
        menu="Advisory CAISO Demand Forecast",
        description="Advisory real-time demand forecast",
        source="spec_2019",
    ),
    Report(
        "SLD_SF_EVAL_DMD_FCST",
        None,
        4,
        1,
        "sufficiency_demand_forecast_hourly",
        menu="Sufficiency Evaluation Demand Forecast",
        description="Demand forecasts for EIM sufficiency evaluation",
        source="spec_2019",
        parameters=(("granularity", "HOURLY"),),
    ),
    Report(
        "SLD_SF_EVAL_DMD_FCST",
        None,
        4,
        1,
        "sufficiency_demand_forecast_15min",
        menu="Sufficiency Evaluation Demand Forecast",
        description="Demand forecasts for EIM sufficiency evaluation",
        source="spec_2019",
        parameters=(("granularity", "15MIN"),),
    ),
    Report(
        "HASP_LOAD_ADJUSTMENT_GRP",
        None,
        13,
        1,
        "hasp_load_adjustments",
        menu="Load Adjustments",
        description="HASP balancing-area load adjustments",
        source="portal",
        endpoint="GroupZip",
    ),
)

SCRAPER = CategoryScraper("system_demand", REPORTS)

DAM_LOAD_FORECAST = REPORTS[0]
