"""Transmission reports from the OASIS menu. See docs/caiso_oasis.md for sources."""

from .models import CategoryScraper, Report

REPORTS = (
    Report(
        "TRNS_CURR_USAGE",
        None,
        1,
        1,
        "current_transmission_usage",
        menu="Current Transmission Usage",
        description="Current Transmission Usage",
        source="spec_2019",
        snapshot=True,
        latest_only=True,
        parameters=(("ti_id", "ALL"), ("ti_direction", "ALL")),
    ),
    Report(
        "TRNS_OUTAGE",
        None,
        1,
        1,
        "transmission_outages",
        menu="Transmission Outages",
        description="Transmission Outages",
        source="spec_2019",
        snapshot=False,
        parameters=(("ti_id", "ALL"), ("ti_direction", "ALL")),
    ),
    Report(
        "TRNS_USAGE",
        "DAM",
        1,
        1,
        "dam_transmission_interface_usage",
        menu="Transmission Interface Usage",
        description="Transmission Interface Usage",
        source="spec_2019",
        snapshot=False,
        parameters=(("ti_id", "ALL"), ("ti_direction", "ALL")),
    ),
    Report(
        "TRNS_ATC",
        "DAM",
        1,
        1,
        "dam_available_transmission_capacity",
        menu="Market Available Transmission Capacity",
        description="Market Available Transmission Capacity",
        source="spec_2019",
        snapshot=False,
        parameters=(("ti_id", "ALL"), ("ti_direction", "ALL")),
    ),
    Report(
        "DAILY_ATC_PWT_REQ_GRP",
        None,
        1,
        1,
        "pwt_available_transfer_capacity",
        menu="ATC for PWT Requests",
        description="Priority-wheeling-through available transfer capacity",
        source="portal",
        endpoint="GroupZip",
        numeric_columns=(
            "pwt_available_capacity",
            "priority_wheel_through_award",
            "avail_trans_capacity",
            "total_trans_capacity",
            "native_load_need_capacity",
            "trans_reliability_margin",
        ),
    ),
    Report(
        "PWT_RESALE_TRANS_GRP",
        None,
        1,
        1,
        "pwt_resale_transactions",
        menu="PWT Resale Transactions",
        description="pwt resale transactions",
        source="portal",
        endpoint="GroupZip",
        snapshot=True,
        date_columns=("transaction_date",),
    ),
)

SCRAPER = CategoryScraper("transmission", REPORTS)
